[package]
name = "solstat"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
solana-sdk = "1.11.4"
arrow = "10.0.0"
solana-client = "1.17.1"
dotenv = "0.15.0"
duckdb = "0.3"